// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine.proto

#include "engine.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace enginePackage {

inline constexpr playActionArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : playerid_{0u},
        cardid_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR playActionArgs::playActionArgs(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct playActionArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR playActionArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~playActionArgsDefaultTypeInternal() {}
  union {
    playActionArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 playActionArgsDefaultTypeInternal _playActionArgs_default_instance_;

inline constexpr placeCardArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : playerid_{0u},
        cardid_{0u},
        baseid_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR placeCardArgs::placeCardArgs(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct placeCardArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR placeCardArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~placeCardArgsDefaultTypeInternal() {}
  union {
    placeCardArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 placeCardArgsDefaultTypeInternal _placeCardArgs_default_instance_;

inline constexpr endTurnArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : playerid_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR endTurnArgs::endTurnArgs(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct endTurnArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR endTurnArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~endTurnArgsDefaultTypeInternal() {}
  union {
    endTurnArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 endTurnArgsDefaultTypeInternal _endTurnArgs_default_instance_;

inline constexpr ServerResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : status_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServerResponse::ServerResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ServerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerResponseDefaultTypeInternal() {}
  union {
    ServerResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerResponseDefaultTypeInternal _ServerResponse_default_instance_;

inline constexpr FileResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : file_content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileResponse::FileResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileResponseDefaultTypeInternal() {}
  union {
    FileResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileResponseDefaultTypeInternal _FileResponse_default_instance_;

inline constexpr FileRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : file_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileRequest::FileRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileRequestDefaultTypeInternal() {}
  union {
    FileRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileRequestDefaultTypeInternal _FileRequest_default_instance_;

inline constexpr ClientNetInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : port_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClientNetInfo::ClientNetInfo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ClientNetInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientNetInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientNetInfoDefaultTypeInternal() {}
  union {
    ClientNetInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientNetInfoDefaultTypeInternal _ClientNetInfo_default_instance_;
}  // namespace enginePackage
static ::_pb::Metadata file_level_metadata_engine_2eproto[7];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_engine_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_engine_2eproto = nullptr;
const ::uint32_t TableStruct_engine_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::enginePackage::placeCardArgs, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::enginePackage::placeCardArgs, _impl_.playerid_),
    PROTOBUF_FIELD_OFFSET(::enginePackage::placeCardArgs, _impl_.cardid_),
    PROTOBUF_FIELD_OFFSET(::enginePackage::placeCardArgs, _impl_.baseid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::enginePackage::playActionArgs, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::enginePackage::playActionArgs, _impl_.playerid_),
    PROTOBUF_FIELD_OFFSET(::enginePackage::playActionArgs, _impl_.cardid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::enginePackage::FileRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::enginePackage::FileRequest, _impl_.file_name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::enginePackage::FileResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::enginePackage::FileResponse, _impl_.file_content_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::enginePackage::endTurnArgs, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::enginePackage::endTurnArgs, _impl_.playerid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::enginePackage::ServerResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::enginePackage::ServerResponse, _impl_.status_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::enginePackage::ClientNetInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::enginePackage::ClientNetInfo, _impl_.port_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::enginePackage::placeCardArgs)},
        {11, -1, -1, sizeof(::enginePackage::playActionArgs)},
        {21, -1, -1, sizeof(::enginePackage::FileRequest)},
        {30, -1, -1, sizeof(::enginePackage::FileResponse)},
        {39, -1, -1, sizeof(::enginePackage::endTurnArgs)},
        {48, -1, -1, sizeof(::enginePackage::ServerResponse)},
        {57, -1, -1, sizeof(::enginePackage::ClientNetInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::enginePackage::_placeCardArgs_default_instance_._instance,
    &::enginePackage::_playActionArgs_default_instance_._instance,
    &::enginePackage::_FileRequest_default_instance_._instance,
    &::enginePackage::_FileResponse_default_instance_._instance,
    &::enginePackage::_endTurnArgs_default_instance_._instance,
    &::enginePackage::_ServerResponse_default_instance_._instance,
    &::enginePackage::_ClientNetInfo_default_instance_._instance,
};
const char descriptor_table_protodef_engine_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014engine.proto\022\renginePackage\"A\n\rplaceCa"
    "rdArgs\022\020\n\010playerId\030\001 \001(\r\022\016\n\006cardId\030\002 \001(\r"
    "\022\016\n\006baseId\030\003 \001(\r\"2\n\016playActionArgs\022\020\n\010pl"
    "ayerId\030\001 \001(\r\022\016\n\006cardId\030\002 \001(\r\" \n\013FileRequ"
    "est\022\021\n\tfile_name\030\001 \001(\t\"$\n\014FileResponse\022\024"
    "\n\014file_content\030\001 \001(\014\"\037\n\013endTurnArgs\022\020\n\010p"
    "layerId\030\001 \001(\r\" \n\016ServerResponse\022\016\n\006Statu"
    "s\030\001 \001(\005\"\035\n\rClientNetInfo\022\014\n\004port\030\001 \001(\r2\375"
    "\002\n\020MainServerEngine\022H\n\tplaceCard\022\034.engin"
    "ePackage.placeCardArgs\032\035.enginePackage.S"
    "erverResponse\022J\n\nplayAction\022\035.enginePack"
    "age.playActionArgs\032\035.enginePackage.Serve"
    "rResponse\022D\n\007endTurn\022\032.enginePackage.end"
    "TurnArgs\032\035.enginePackage.ServerResponse\022"
    "I\n\ninitClient\022\034.enginePackage.ClientNetI"
    "nfo\032\035.enginePackage.ServerResponse\022B\n\007Ge"
    "tFile\022\032.enginePackage.FileRequest\032\033.engi"
    "nePackage.FileResponse2\376\001\n\021SlaveServerEn"
    "gine\022M\n\016placeCardSlave\022\034.enginePackage.p"
    "laceCardArgs\032\035.enginePackage.ServerRespo"
    "nse\022O\n\017playActionSlave\022\035.enginePackage.p"
    "layActionArgs\032\035.enginePackage.ServerResp"
    "onse\022I\n\014endTurnSlave\022\032.enginePackage.end"
    "TurnArgs\032\035.enginePackage.ServerResponseb"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_engine_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_engine_2eproto = {
    false,
    false,
    967,
    descriptor_table_protodef_engine_2eproto,
    "engine.proto",
    &descriptor_table_engine_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_engine_2eproto::offsets,
    file_level_metadata_engine_2eproto,
    file_level_enum_descriptors_engine_2eproto,
    file_level_service_descriptors_engine_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_engine_2eproto_getter() {
  return &descriptor_table_engine_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_engine_2eproto(&descriptor_table_engine_2eproto);
namespace enginePackage {
// ===================================================================

class placeCardArgs::_Internal {
 public:
};

placeCardArgs::placeCardArgs(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:enginePackage.placeCardArgs)
}
placeCardArgs::placeCardArgs(
    ::google::protobuf::Arena* arena, const placeCardArgs& from)
    : placeCardArgs(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE placeCardArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void placeCardArgs::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, playerid_),
           0,
           offsetof(Impl_, baseid_) -
               offsetof(Impl_, playerid_) +
               sizeof(Impl_::baseid_));
}
placeCardArgs::~placeCardArgs() {
  // @@protoc_insertion_point(destructor:enginePackage.placeCardArgs)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void placeCardArgs::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void placeCardArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:enginePackage.placeCardArgs)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.playerid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.baseid_) -
      reinterpret_cast<char*>(&_impl_.playerid_)) + sizeof(_impl_.baseid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* placeCardArgs::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> placeCardArgs::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_placeCardArgs_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 playerId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(placeCardArgs, _impl_.playerid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(placeCardArgs, _impl_.playerid_)}},
    // uint32 cardId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(placeCardArgs, _impl_.cardid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(placeCardArgs, _impl_.cardid_)}},
    // uint32 baseId = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(placeCardArgs, _impl_.baseid_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(placeCardArgs, _impl_.baseid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 playerId = 1;
    {PROTOBUF_FIELD_OFFSET(placeCardArgs, _impl_.playerid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 cardId = 2;
    {PROTOBUF_FIELD_OFFSET(placeCardArgs, _impl_.cardid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 baseId = 3;
    {PROTOBUF_FIELD_OFFSET(placeCardArgs, _impl_.baseid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* placeCardArgs::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:enginePackage.placeCardArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 playerId = 1;
  if (this->_internal_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_playerid(), target);
  }

  // uint32 cardId = 2;
  if (this->_internal_cardid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_cardid(), target);
  }

  // uint32 baseId = 3;
  if (this->_internal_baseid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_baseid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:enginePackage.placeCardArgs)
  return target;
}

::size_t placeCardArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:enginePackage.placeCardArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 playerId = 1;
  if (this->_internal_playerid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_playerid());
  }

  // uint32 cardId = 2;
  if (this->_internal_cardid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_cardid());
  }

  // uint32 baseId = 3;
  if (this->_internal_baseid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_baseid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData placeCardArgs::_class_data_ = {
    placeCardArgs::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* placeCardArgs::GetClassData() const {
  return &_class_data_;
}

void placeCardArgs::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<placeCardArgs*>(&to_msg);
  auto& from = static_cast<const placeCardArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:enginePackage.placeCardArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_playerid() != 0) {
    _this->_internal_set_playerid(from._internal_playerid());
  }
  if (from._internal_cardid() != 0) {
    _this->_internal_set_cardid(from._internal_cardid());
  }
  if (from._internal_baseid() != 0) {
    _this->_internal_set_baseid(from._internal_baseid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void placeCardArgs::CopyFrom(const placeCardArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:enginePackage.placeCardArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool placeCardArgs::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* placeCardArgs::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void placeCardArgs::InternalSwap(placeCardArgs* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(placeCardArgs, _impl_.baseid_)
      + sizeof(placeCardArgs::_impl_.baseid_)
      - PROTOBUF_FIELD_OFFSET(placeCardArgs, _impl_.playerid_)>(
          reinterpret_cast<char*>(&_impl_.playerid_),
          reinterpret_cast<char*>(&other->_impl_.playerid_));
}

::google::protobuf::Metadata placeCardArgs::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_engine_2eproto_getter, &descriptor_table_engine_2eproto_once,
      file_level_metadata_engine_2eproto[0]);
}
// ===================================================================

class playActionArgs::_Internal {
 public:
};

playActionArgs::playActionArgs(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:enginePackage.playActionArgs)
}
playActionArgs::playActionArgs(
    ::google::protobuf::Arena* arena, const playActionArgs& from)
    : playActionArgs(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE playActionArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void playActionArgs::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, playerid_),
           0,
           offsetof(Impl_, cardid_) -
               offsetof(Impl_, playerid_) +
               sizeof(Impl_::cardid_));
}
playActionArgs::~playActionArgs() {
  // @@protoc_insertion_point(destructor:enginePackage.playActionArgs)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void playActionArgs::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void playActionArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:enginePackage.playActionArgs)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.playerid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.cardid_) -
      reinterpret_cast<char*>(&_impl_.playerid_)) + sizeof(_impl_.cardid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* playActionArgs::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> playActionArgs::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_playActionArgs_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint32 cardId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(playActionArgs, _impl_.cardid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(playActionArgs, _impl_.cardid_)}},
    // uint32 playerId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(playActionArgs, _impl_.playerid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(playActionArgs, _impl_.playerid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 playerId = 1;
    {PROTOBUF_FIELD_OFFSET(playActionArgs, _impl_.playerid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 cardId = 2;
    {PROTOBUF_FIELD_OFFSET(playActionArgs, _impl_.cardid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* playActionArgs::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:enginePackage.playActionArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 playerId = 1;
  if (this->_internal_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_playerid(), target);
  }

  // uint32 cardId = 2;
  if (this->_internal_cardid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_cardid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:enginePackage.playActionArgs)
  return target;
}

::size_t playActionArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:enginePackage.playActionArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 playerId = 1;
  if (this->_internal_playerid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_playerid());
  }

  // uint32 cardId = 2;
  if (this->_internal_cardid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_cardid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData playActionArgs::_class_data_ = {
    playActionArgs::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* playActionArgs::GetClassData() const {
  return &_class_data_;
}

void playActionArgs::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<playActionArgs*>(&to_msg);
  auto& from = static_cast<const playActionArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:enginePackage.playActionArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_playerid() != 0) {
    _this->_internal_set_playerid(from._internal_playerid());
  }
  if (from._internal_cardid() != 0) {
    _this->_internal_set_cardid(from._internal_cardid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void playActionArgs::CopyFrom(const playActionArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:enginePackage.playActionArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool playActionArgs::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* playActionArgs::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void playActionArgs::InternalSwap(playActionArgs* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(playActionArgs, _impl_.cardid_)
      + sizeof(playActionArgs::_impl_.cardid_)
      - PROTOBUF_FIELD_OFFSET(playActionArgs, _impl_.playerid_)>(
          reinterpret_cast<char*>(&_impl_.playerid_),
          reinterpret_cast<char*>(&other->_impl_.playerid_));
}

::google::protobuf::Metadata playActionArgs::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_engine_2eproto_getter, &descriptor_table_engine_2eproto_once,
      file_level_metadata_engine_2eproto[1]);
}
// ===================================================================

class FileRequest::_Internal {
 public:
};

FileRequest::FileRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:enginePackage.FileRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : file_name_(arena, from.file_name_),
        _cached_size_{0} {}

FileRequest::FileRequest(
    ::google::protobuf::Arena* arena,
    const FileRequest& from)
    : ::google::protobuf::Message(arena) {
  FileRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:enginePackage.FileRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : file_name_(arena),
        _cached_size_{0} {}

inline void FileRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileRequest::~FileRequest() {
  // @@protoc_insertion_point(destructor:enginePackage.FileRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.file_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:enginePackage.FileRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.file_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> FileRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string file_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.file_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string file_name = 1;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.file_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\11\0\0\0\0\0\0"
    "enginePackage.FileRequest"
    "file_name"
  }},
};

::uint8_t* FileRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:enginePackage.FileRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string file_name = 1;
  if (!this->_internal_file_name().empty()) {
    const std::string& _s = this->_internal_file_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "enginePackage.FileRequest.file_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:enginePackage.FileRequest)
  return target;
}

::size_t FileRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:enginePackage.FileRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string file_name = 1;
  if (!this->_internal_file_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_file_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileRequest::_class_data_ = {
    FileRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileRequest::GetClassData() const {
  return &_class_data_;
}

void FileRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileRequest*>(&to_msg);
  auto& from = static_cast<const FileRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:enginePackage.FileRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_file_name().empty()) {
    _this->_internal_set_file_name(from._internal_file_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileRequest::CopyFrom(const FileRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:enginePackage.FileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileRequest::InternalSwap(FileRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_name_, &other->_impl_.file_name_, arena);
}

::google::protobuf::Metadata FileRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_engine_2eproto_getter, &descriptor_table_engine_2eproto_once,
      file_level_metadata_engine_2eproto[2]);
}
// ===================================================================

class FileResponse::_Internal {
 public:
};

FileResponse::FileResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:enginePackage.FileResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : file_content_(arena, from.file_content_),
        _cached_size_{0} {}

FileResponse::FileResponse(
    ::google::protobuf::Arena* arena,
    const FileResponse& from)
    : ::google::protobuf::Message(arena) {
  FileResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:enginePackage.FileResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : file_content_(arena),
        _cached_size_{0} {}

inline void FileResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileResponse::~FileResponse() {
  // @@protoc_insertion_point(destructor:enginePackage.FileResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.file_content_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:enginePackage.FileResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.file_content_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FileResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes file_content = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.file_content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes file_content = 1;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.file_content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FileResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:enginePackage.FileResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes file_content = 1;
  if (!this->_internal_file_content().empty()) {
    const std::string& _s = this->_internal_file_content();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:enginePackage.FileResponse)
  return target;
}

::size_t FileResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:enginePackage.FileResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes file_content = 1;
  if (!this->_internal_file_content().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_file_content());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileResponse::_class_data_ = {
    FileResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileResponse::GetClassData() const {
  return &_class_data_;
}

void FileResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileResponse*>(&to_msg);
  auto& from = static_cast<const FileResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:enginePackage.FileResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_file_content().empty()) {
    _this->_internal_set_file_content(from._internal_file_content());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileResponse::CopyFrom(const FileResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:enginePackage.FileResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileResponse::InternalSwap(FileResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_content_, &other->_impl_.file_content_, arena);
}

::google::protobuf::Metadata FileResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_engine_2eproto_getter, &descriptor_table_engine_2eproto_once,
      file_level_metadata_engine_2eproto[3]);
}
// ===================================================================

class endTurnArgs::_Internal {
 public:
};

endTurnArgs::endTurnArgs(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:enginePackage.endTurnArgs)
}
endTurnArgs::endTurnArgs(
    ::google::protobuf::Arena* arena, const endTurnArgs& from)
    : endTurnArgs(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE endTurnArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void endTurnArgs::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.playerid_ = {};
}
endTurnArgs::~endTurnArgs() {
  // @@protoc_insertion_point(destructor:enginePackage.endTurnArgs)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void endTurnArgs::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void endTurnArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:enginePackage.endTurnArgs)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.playerid_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* endTurnArgs::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> endTurnArgs::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_endTurnArgs_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint32 playerId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(endTurnArgs, _impl_.playerid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(endTurnArgs, _impl_.playerid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 playerId = 1;
    {PROTOBUF_FIELD_OFFSET(endTurnArgs, _impl_.playerid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* endTurnArgs::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:enginePackage.endTurnArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 playerId = 1;
  if (this->_internal_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_playerid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:enginePackage.endTurnArgs)
  return target;
}

::size_t endTurnArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:enginePackage.endTurnArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 playerId = 1;
  if (this->_internal_playerid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_playerid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData endTurnArgs::_class_data_ = {
    endTurnArgs::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* endTurnArgs::GetClassData() const {
  return &_class_data_;
}

void endTurnArgs::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<endTurnArgs*>(&to_msg);
  auto& from = static_cast<const endTurnArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:enginePackage.endTurnArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_playerid() != 0) {
    _this->_internal_set_playerid(from._internal_playerid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void endTurnArgs::CopyFrom(const endTurnArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:enginePackage.endTurnArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool endTurnArgs::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* endTurnArgs::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void endTurnArgs::InternalSwap(endTurnArgs* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.playerid_, other->_impl_.playerid_);
}

::google::protobuf::Metadata endTurnArgs::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_engine_2eproto_getter, &descriptor_table_engine_2eproto_once,
      file_level_metadata_engine_2eproto[4]);
}
// ===================================================================

class ServerResponse::_Internal {
 public:
};

ServerResponse::ServerResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:enginePackage.ServerResponse)
}
ServerResponse::ServerResponse(
    ::google::protobuf::Arena* arena, const ServerResponse& from)
    : ServerResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ServerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ServerResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
ServerResponse::~ServerResponse() {
  // @@protoc_insertion_point(destructor:enginePackage.ServerResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ServerResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ServerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:enginePackage.ServerResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ServerResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ServerResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ServerResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 Status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServerResponse, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ServerResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 Status = 1;
    {PROTOBUF_FIELD_OFFSET(ServerResponse, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ServerResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:enginePackage.ServerResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 Status = 1;
  if (this->_internal_status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:enginePackage.ServerResponse)
  return target;
}

::size_t ServerResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:enginePackage.ServerResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 Status = 1;
  if (this->_internal_status() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ServerResponse::_class_data_ = {
    ServerResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ServerResponse::GetClassData() const {
  return &_class_data_;
}

void ServerResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ServerResponse*>(&to_msg);
  auto& from = static_cast<const ServerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:enginePackage.ServerResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServerResponse::CopyFrom(const ServerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:enginePackage.ServerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ServerResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ServerResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ServerResponse::InternalSwap(ServerResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata ServerResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_engine_2eproto_getter, &descriptor_table_engine_2eproto_once,
      file_level_metadata_engine_2eproto[5]);
}
// ===================================================================

class ClientNetInfo::_Internal {
 public:
};

ClientNetInfo::ClientNetInfo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:enginePackage.ClientNetInfo)
}
ClientNetInfo::ClientNetInfo(
    ::google::protobuf::Arena* arena, const ClientNetInfo& from)
    : ClientNetInfo(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ClientNetInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ClientNetInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.port_ = {};
}
ClientNetInfo::~ClientNetInfo() {
  // @@protoc_insertion_point(destructor:enginePackage.ClientNetInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ClientNetInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ClientNetInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:enginePackage.ClientNetInfo)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.port_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ClientNetInfo::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ClientNetInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ClientNetInfo_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint32 port = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ClientNetInfo, _impl_.port_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ClientNetInfo, _impl_.port_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 port = 1;
    {PROTOBUF_FIELD_OFFSET(ClientNetInfo, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ClientNetInfo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:enginePackage.ClientNetInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:enginePackage.ClientNetInfo)
  return target;
}

::size_t ClientNetInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:enginePackage.ClientNetInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ClientNetInfo::_class_data_ = {
    ClientNetInfo::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ClientNetInfo::GetClassData() const {
  return &_class_data_;
}

void ClientNetInfo::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ClientNetInfo*>(&to_msg);
  auto& from = static_cast<const ClientNetInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:enginePackage.ClientNetInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClientNetInfo::CopyFrom(const ClientNetInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:enginePackage.ClientNetInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ClientNetInfo::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ClientNetInfo::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ClientNetInfo::InternalSwap(ClientNetInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.port_, other->_impl_.port_);
}

::google::protobuf::Metadata ClientNetInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_engine_2eproto_getter, &descriptor_table_engine_2eproto_once,
      file_level_metadata_engine_2eproto[6]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace enginePackage
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
