name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: oprypin/install-sfml@v1
        id: install-sfml
      - run: sudo apt install -y nlohmann-json3-dev
      - run: sudo apt install -y fluxbox
      - run: mkdir build && cd build && cmake -DSMFL_INCLUDE_DIR=${{steps.install-sfml.outputs.path}} .. && make 
      - run: |
          export DISPLAY=:99
          echo $DISPLAY
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sleep 5
          fluxbox > /dev/null 2>&1 &
          sleep 5
          sh -c "timeout 10s ./game" || 
          if [ $? -eq 124 ]; then
            exit 0
          else
            exit 1
          fi
        working-directory: build
    
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "src/**/*.h,src/**/*.cpp,src/**/*.hpp,include/**/*.h,include/**/*.hpp"
          excludes: "some_file.cpp" ## action is not working correctly if exclude field is empty
          style: file

